version: "${VERSION}"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  api-gateway:
    build:
      context: ./ApiGateway/ApiGateway
      dockerfile: Dockerfile
    expose:
      - ${API_GATEWAY_PORT}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${API_GATEWAY_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
  
  auth-service:
    build:
      context: ./AuthService/AuthService
      dockerfile: Dockerfile
    expose:
      - ${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${AUTH_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
      PROFILE_SERVICE_URL: http://profile-service:${PROFILE_SERVICE_PORT}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started

  profile-service:
    build:
      context: ./ProfileService/ProfileService
      dockerfile: Dockerfile
    expose:
      - ${PROFILE_SERVICE_PORT}
    ports:
      - "${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${PROFILE_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
      JOB_OFFER_SERVICE_URL: http://job-offer-service:${JOB_OFFER_SERVICE_PORT}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started
        
  event-service:
    build:
      context: ./EventService/EventService
      dockerfile: Dockerfile
    expose:
      - ${EVENT_SERVICE_PORT}
    ports:
      - "${EVENT_SERVICE_PORT}:${EVENT_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${EVENT_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started

  notification-service:
    build:
      context: ./NotificationService/NotificationService
      dockerfile: Dockerfile
    expose:
      - ${NOTIFICATION_SERVICE_PORT}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${NOTIFICATION_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started
        
  post-service:
    build:
      context: ./PostService/PostService
      dockerfile: Dockerfile
    expose:
      - ${POST_SERVICE_PORT}
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${POST_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started

  job-offer-service:
    build:
      context: ./JobOfferService/JobOfferService
      dockerfile: Dockerfile
    expose:
      - ${JOB_OFFER_SERVICE_PORT}
    ports:
      - "${JOB_OFFER_SERVICE_PORT}:${JOB_OFFER_SERVICE_PORT}"
    environment:
      "MongoDbSettings:ConnectionString": "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017"
      ASPNETCORE_URLS: http://+:${JOB_OFFER_SERVICE_PORT}
    networks:
      - servers
      - monitoring
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started

  message-service:
    build:
      context: ./MessageService/MessageService
      dockerfile: Dockerfile
    expose:
      - ${MESSAGE_SERVICE_PORT}
    ports:
      - "${MESSAGE_SERVICE_PORT}:${MESSAGE_SERVICE_PORT}"
    environment:
      "MongoDbSettings:ConnectionString": "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017"
      ASPNETCORE_URLS: http://+:${MESSAGE_SERVICE_PORT}
    networks:
      - servers
      - monitoring
    depends_on:
      mongo:
        condition: service_healthy
      nats:
        condition: service_started
      jaeger:
        condition: service_started

  nats:
    image: 'nats:2'
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - servers

  db:
    image: postgres
    container_name: local_pgdb
    networks:
       - servers
       - monitoring
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      retries: 3
      interval: 5s
      timeout: 5s
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    logging: *fluent-bit

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    networks:
       - servers
       - monitoring
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - local_mongodata:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    networks:
      - servers
      - monitoring
    restart: always
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  local_pgdata:
  local_mongodata:
  pgadmin-data:

networks:
  servers:
    name: servers
    driver: bridge
  monitoring:
    external: true
