version: "${VERSION}"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: ${FLUENT_BIT_ADDRESS}:24224

services:
  profile-service:
    image: evaj10/profile-service
    ports:
      # - "${PROFILE_SERVICE_PORT}:80"
      - "${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${PROFILE_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started

  post-service:
    # build:
    #   context: .././PostService/PostService
    #   dockerfile: Dockerfile
    image: evaj10/post-service:1.0.0-develop.5
    ports:
      # - "${POST_SERVICE_PORT}:80"
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    environment:
      ASPNETCORE_URLS: http://+:${POST_SERVICE_PORT}
      DB_HOST: ${POSTGRES_CONNECTION_STRING_VALUE}
    networks:
      - servers
      - monitoring
    logging: *fluent-bit
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started

  nats:
    image: 'nats:2'
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - servers

  db:
    image: postgres
    container_name: local_pgdb
    networks:
       - servers
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      retries: 3
      interval: 5s
      timeout: 5s
    volumes:
      - local_pgdata:/var/lib/postgresql/data
   
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    networks:
      - servers
    restart: always
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  servers:
    name: servers
    driver: bridge
  monitoring:
    external: true