  # my global config
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).

  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  rule_files:
   - "rules/recording_rules.yml"

  scrape_configs:
    - job_name: 'prometheus'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ['localhost:9090']


    - job_name: 'api-gateway'
      static_configs:
        - targets: ['host.docker.internal:5000']
    
    - job_name: 'auth-service'
      static_configs:
        - targets: ['host.docker.internal:5001']

    - job_name: 'message-service'
      static_configs:
        - targets: ['host.docker.internal:5002']

    - job_name: 'profile-service'
      static_configs:
        - targets: ['host.docker.internal:5003']

    - job_name: 'post-service'
      static_configs:
        - targets: ['host.docker.internal:5004']

    - job_name: 'notification-service'
      static_configs:
        - targets: ['host.docker.internal:5005']

    - job_name: 'job-offer-service'
      static_configs:
        - targets: ['host.docker.internal:5006']


    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: 'grafana'
      static_configs:
        - targets: ['grafana:3000']

    - job_name: 'cAdvisor'
      static_configs:
        - targets: [ 'cadvisor:8080' ]
